### ISSUE TITLE
Click on settings save sometimes warp to network view

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/cli#305]
Sometimes when we click on the save button (settings view) it warp/teleport us to the network view (seems like a bug)

**Comment by kishore881** [comment]
whats the ideal behavior here..? its always taking me to network view after i click on save. similar to what hitting N does in Settings view

**Comment by kishore881** [comment]
the if in main.js:77:5 is evaluating to false since `networkNavigation.currentNodeParams` is `undefined` and `currentNodeParams` is initialised to `null` causing this error when params.nodes is accessed in network.js:211. 

<img width="656" alt="Screenshot 2023-12-04 at 10 38 23 PM" src="https://github.com/NodeSecure/cli/assets/49707819/d606ffe8-9b9a-4a81-aec8-4d58baab72ca">

whats the var currentNodeParams doing here..? its initialised to null, but never updated after that

**Comment by fraxken** [comment]
Probably related to recent @PierreDemailly updates on network navigation

**Comment by fraxken** [comment]
Should be ok with this fix: https://github.com/NodeSecure/cli/pull/313
